doc: |
  Test for the IPC of HOMI
  ========================

  This task assumes you have the following keys defined, "xal.backend",
  "device.{uri, be}", and "data.test_file". For example:

    [xal]
    backend = 2

    [device]
    uri = "/dev/nvme0n1"
    be = "linux"

    [data]
    test_file = "/mnt/path/to/file_on_device"

steps:
- name: precondition
  run: | 
    cd ~/git/xnvme; make clean config build install;
    cd ~/git/xal; make;
    cd ~/git/homi; make;
    sed -i 's|devices = \[\]|devices = [ { uri = "{{ config.device.uri }}", be = "{{ config.device.be }}"} ]|' /etc/homi/homi.conf
    sed -i 's|log_level = 2|log_level = 4|' /etc/homi/homi.conf
    sed -i 's|backend = 2|backend = {{ config.xal.backend }}|' /etc/homi/homi.conf
    sed -i 's|watchmode = 2|watchmode = 0|' /etc/homi/homi.conf

- name: transfer1
  uses: core.put
  with:
    src: "{{ local.env.HOME }}/git/homi/cijoe/auxilliary/test-connect-xal.c"
    dst: "/tmp/test-connect-xal.c"

- name: transfer2
  uses: core.put
  with:
    src: "{{ local.env.HOME }}/git/homi/cijoe/auxilliary/test-connect-xnvme.c"
    dst: "/tmp/test-connect-xnvme.c"

- name: start
  run: |
    cd ~/git/homi; make start; make log;

- name: test_xal
  run: |
    gcc /tmp/test-connect-xal.c -o /tmp/test -lhomic -lxal
    /tmp/test {{ config.device.uri }} {{ config.data.test_file }}

- name: test_xnvme
  run: |
    gcc /tmp/test-connect-xnvme.c -o /tmp/test -lhomic -lxal -lxnvme
    /tmp/test {{ config.device.uri }} {{ config.device.be }} 42

- name: stop
  run: |
    cd ~/git/homi; make stop; make log;
